<?php 
	session_start();
	require_once('connect.php');
	require_once('users/usersTrait.php');
	require_once('users/adminLogin.php');
	require_once('users/users.php');
	require_once('validate.php');
	require_once('layouts/app.php');
	require_once('auth/login.php');
	require_once('layouts/app-footer.php');